### ISSUE TITLE
ide: crash after removing require composition and start syskit instance

### ISSUE THREAD

**Issue by renan028** [rock-core/tools-syskit#141]
before start, I reload the models

```
= accessing a disposed task context (ArgumentError)
= Backtrace
| 
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/ruby_tasks/task_context.rb:250:in `do_create_port'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/ruby_tasks/task_context.rb:250:in `create_port'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/ruby_tasks/task_context.rb:87:in `create_input_port'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/ports_base.rb:237:in `block in reader'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/base.rb:88:in `synchronize'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/base.rb:88:in `ruby_task_access'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/ports_base.rb:236:in `reader'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/task_context.rb:184:in `state_reader'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/task_context.rb:198:in `peek_state'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/task_context_base.rb:748:in `states'
|   /home/renan/dev/emma/tools/utilrb/lib/utilrb/thread_pool.rb:440:in `sync'
|   /home/renan/dev/emma/tools/orocos.rb/lib/orocos/async/task_context_base.rb:72:in `block in initialize'
|   /home/renan/dev/emma/tools/utilrb/lib/utilrb/thread_pool.rb:191:in `execute'
|   /home/renan/dev/emma/tools/utilrb/lib/utilrb/thread_pool.rb:590:in `block in spawn_thread'
|   /home/renan/dev/emma/tools/utilrb/lib/utilrb/event_loop.rb:622:in `step'
|   /home/renan/dev/emma/gui/vizkit/lib/vizkit/vizkit.rb:142:in `block in exec'
|   /home/renan/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.4/lib/Qt/qtruby4.rb:2470:in `invoke'
|   /home/renan/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.4/lib/Qt/qtruby4.rb:479:in `qt_metacall'
|   /home/renan/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.4/lib/Qt/qtruby4.rb:479:in `method_missing'
|   /home/renan/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.4/lib/Qt/qtruby4.rb:479:in `exec'
|   /home/renan/dev/emma/gui/vizkit/lib/vizkit/vizkit.rb:146:in `exec'
|   /home/renan/dev/emma/tools/syskit/bin/syskit:20:in `<main>'
= 

```

**Comment by doudou** [comment]
Should be fixed now, by #173
