### ISSUE TITLE
all TaskContext tests must be run in live mode

### ISSUE THREAD

**Issue by doudou** [rock-core/tools-syskit#54]
The simulation mode seems to be broken somehow for task contexts (works fine for e.g. composition tests though)

~~~
13:39:11.651 (Roby) = mission failed: OroGen::AuvControl::PIDController:0x5a5b540{orocos_name => task_under_test, conf => [default]}[]
13:39:11.651 (Roby) | uncaught exception in the command of the start event of Deployments::OrogenDefaultAuvControl__PIDController:0x5a81330
13:39:11.651 (Roby) | /home/doudou/dev/flat_fish/tools/orocos.rb/lib/orocos/ruby_tasks/process_manager.rb:48:in `start': task_under_test is already started in #<Orocos::RubyTasks::ProcessManager:0x0000000540b5c8> (ArgumentError)
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/orocos.rb/lib/orocos/ruby_tasks/process_manager.rb:48:in `start'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/syskit/lib/syskit/deployment.rb:164:in `block in <class:Deployment>'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/models/task.rb:344:in `call'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/models/task.rb:344:in `block in define_command_method'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/task_event_generator.rb:25:in `default_command'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:201:in `[]'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:201:in `block (2 levels) in call_without_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:658:in `propagation_context'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:197:in `block in call_without_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:189:in `catch'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:189:in `call_without_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/task_event_generator.rb:192:in `call_without_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:994:in `block (2 levels) in event_propagation_step'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:658:in `propagation_context'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:992:in `block in event_propagation_step'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:569:in `block in gather_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:658:in `propagation_context'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:569:in `gather_propagation'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:991:in `event_propagation_step'
13:39:11.651 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:801:in `block in event_propagation_phase'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:779:in `gather_errors'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:797:in `event_propagation_phase'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:1367:in `block in process_events_synchronous'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:612:in `gather_framework_errors'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/execution_engine.rb:1343:in `process_events_synchronous'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:671:in `block in emit'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/support.rb:176:in `synchronize'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/event_generator.rb:667:in `emit'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/task.rb:758:in `emit'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/syskit/lib/syskit/test/base.rb:101:in `syskit_run_deployer'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/syskit/lib/syskit/test/network_manipulation.rb:202:in `deploy'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/bundles/rock_auv/test/orogen/test_auv_control.rb:100:in `block (3 levels) in <module:AuvControl>'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/test/spec.rb:49:in `instance_eval'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/test/spec.rb:49:in `block in it'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:108:in `block (3 levels) in run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:206:in `capture_exceptions'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:105:in `block (2 levels) in run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:258:in `time_it'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:104:in `block in run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:327:in `on_signal'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:278:in `with_info_handler'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest/test.rb:103:in `run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/test/spec.rb:231:in `run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:774:in `run_one_method'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:301:in `run_one_method'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:289:in `block (2 levels) in run'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:288:in `each'
13:39:11.652 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:288:in `block in run'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:327:in `on_signal'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:314:in `with_info_handler'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:287:in `run'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:150:in `block in __run'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:150:in `map'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:150:in `__run'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/.gems/gems/minitest-5.5.1/lib/minitest.rb:127:in `run'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/app/scripts/test.rb:103:in `block in <top (required)>'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/exceptions.rb:428:in `display_exception'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/tools/roby/lib/roby/app/scripts/test.rb:70:in `<top (required)>'
13:39:11.653 (Roby) |   /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
13:39:11.653 (Roby) |   /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/tools/syskit/bin/syskit:28:in `rescue in <main>'
13:39:11.653 (Roby) |   /home/doudou/dev/flat_fish/tools/syskit/bin/syskit:24:in `<main>'
13:39:11.653 (Roby) = Backtrace
~~~

**Comment by doudou** [comment]
Seems to be fixed ...
