### ISSUE TITLE
system management tutorial error

### ISSUE THREAD

**Issue by gustavoneves12** [rock-core/tools-syskit#61]
I was studying the system management tutorial and the error below is showed when I execute the command <b>syskit instanciate scripts/01_joystick.rb</b>:

```
15:40:51.381 (Robot) ignored file scripts/01_joystick.rb
15:40:51.381 (Roby) could not find any connections from Tutorials::RockControl.cmd_child[OroGen::Controldev::JoystickTask] to Tutorials::RockControl.rock_child[OroGen::RockTutorial::RockTutorialControl]
15:40:51.381 (Roby)   the outputs of Tutorials::RockControl.cmd_child[OroGen::Controldev::JoystickTask] are
15:40:51.381 (Roby)     raw_command[/controldev/RawCommand],
15:40:51.381 (Roby)     state[/int32_t]
15:40:51.381 (Roby)   the inputs of Tutorials::RockControl.rock_child[OroGen::RockTutorial::RockTutorialControl] are
15:40:51.381 (Roby)     motion_command[/base/commands/Motion2D]
15:40:51.381 (Roby) = Backtrace
15:40:51.382 (Roby)
15:40:51.382 (Roby)   /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/connection_graphs.rb:291:in `connect'
15:40:51.382 (Roby)   /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/models/composition_child.rb:83:in `connect_to'
15:40:51.382 (Roby)   ./scripts/01_joystick.rb:22:in `<class:RockControl>'
15:40:51.382 (Roby)   ./scripts/01_joystick.rb:11:in `<module:Tutorials>'
15:40:51.382 (Roby)   ./scripts/01_joystick.rb:9:in `<top (required)>'
15:40:51.382 (Roby)   /home/gustavoneves/rock-robotics/tools/syskit/bin/syskit:19:in `<main>'
15:40:51.382 (Roby) =
15:40:51.384 (Robot) loaded Roby application in 0.423 seconds
```

My rock installation is the master branch.

**Comment by doudou** [comment]
This is being 100% rewritten from scratch.
